/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//package mini.project.hospital.management.system;

import javax.swing.JFrame;

/**
 *
 * @author Nandana Nair
 */
public class Contactus extends javax.swing.JFrame {

    /**
     * Creates new form contactus
     */
    public Contactus() {
        initComponents();
        //this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("CONTACT US");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(550, 60, 370, 58);

        jLabel3.setText("ACCIDENT AND EMERGENCY CARE");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(510, 170, 210, 41);

        jLabel4.setText("022 71023322 / 3323");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(760, 170, 186, 41);

        jLabel5.setText("BLOOD BANK");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(570, 210, 90, 14);

        jLabel6.setText("022 25763355");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(760, 210, 69, 14);

        jLabel7.setText("OPD APPOINTMENT");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(540, 250, 130, 14);

        jLabel8.setText("022 25763500");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(760, 250, 69, 14);

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 153));
        jLabel9.setText("HELPLINES");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(670, 120, 100, 32);

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 153));
        jLabel10.setText("MAIL US AT");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(670, 290, 100, 18);

        jLabel11.setText("For Appointment Email:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(550, 330, 153, 14);

        jLabel12.setText("For feedback:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(570, 360, 93, 14);

        jLabel13.setText("For general/business related queries :");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(510, 390, 182, 14);

        jLabel14.setText("opdvisit@cityhospital.org");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(760, 330, 134, 14);

        jLabel15.setText("wecare@cityhospital.org");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(760, 360, 119, 14);

        jLabel16.setText("reachus@cityhealthcare.com");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(760, 390, 150, 14);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 153));
        jLabel2.setText("ADDRESS");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(670, 520, 90, 18);

        jLabel17.setText("Tower A, Unitech Business Park, Block - F, South City 1, Sector - 41,Gurgaon, Haryana - 122001");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(500, 550, 518, 14);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/contactUs1.png"))); // NOI18N
        jPanel1.add(jLabel19);
        jLabel19.setBounds(350, 50, 128, 140);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/contactUs2.png"))); // NOI18N
        jPanel1.add(jLabel20);
        jLabel20.setBounds(1030, 50, 120, 128);

        jButton1.setText("BACK TO HOME PAGE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(650, 580, 160, 23);

        jLabel18.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 51, 153));
        jLabel18.setText("CHAT WITH US");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(640, 420, 140, 18);

        jLabel21.setText("WhatsApp Number:");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(550, 450, 111, 14);

        jLabel22.setText("9820378001");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(760, 450, 82, 14);

        jLabel23.setText("Facebook:");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(560, 480, 67, 14);

        jLabel24.setText("@CityHospital");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(760, 480, 82, 14);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cont.png"))); // NOI18N
        jPanel1.add(jLabel25);
        jLabel25.setBounds(0, -60, 1760, 1020);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1934, 1117));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        HomePage pa =new HomePage();
        pa.show();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contactus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contactus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contactus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contactus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contactus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
